---
# Tools using the Chemistry Development Kit
kind: DataManagerJobDefinition
kind-version: '2021.1'
name: ChemAxon molecular properties
collection: chemaxon

jobs:
  chemaxon-molecular-props-simple:
    name: ChemAxon simple molecular properties
    description: >-
      Calculate molecular properties using ChemAxon tools.
    version: '1.0.0'
    category: molecular properties
    keywords:
    - chemaxon
    - properties
    - atomcount
    - bondcount
    - logp
    - logd
    - hbd
    - hba
    - h-bond
    image:
      name: informaticsmatters/squonk2-chemaxon
      tag: latest
      project-directory: /data
      working-directory: /data
      fix-permissions: true
      file:
      - name: /usr/local/license.cxl
        content-from:
          account-server-asset:
            name: chemaxon-license-file
      environment:
      - name: CHEMAXON_LICENSE_URL
        value-from:
          constant:
            value: /usr/local/license.cxl
    # The container has no entrypoint so this is the command that is executed.
    # The CLASSPATH environment variable in the container is set.
    command: >-
      java squonk.jobs.chemaxon.SimpleCalcs
      --input '{{ inputFile }}'
      --output '{{ outputFile }}'
      {% if header is defined and header %}--header {{ header }}{% endif %}
      {% if molecularWeight is defined and molecularWeight %}--molecularWeight{% endif %}
      {% if molecularFormula is defined and molecularFormula %}--molecularFormula{% endif %}
      {% if atomCount is defined and atomCount %}--atomCount{% endif %}
      {% if heavyAtomCount is defined and heavyAtomCount%}--heavyAtomCount{% endif %}
      {% if bondCount is defined and bondCount %}--bondCount{% endif %}
      {% if logp is defined and logp %}--logp{% endif %}
      {% if logd is defined and logd %}--logd{% endif %}
      {% if hba is defined and hba %}--hba{% endif %}
      {% if hbd is defined and hbd %}--hbd{% endif %}
      {% if ringCount is defined and ringCount %}--ringCount{% endif %}
      {% if ringAtomCount is defined and ringAtomCount %}--ringAtomCount{% endif %}
      {% if aromaticRingCount is defined and aromaticRingCount %}--aromaticRingCount{% endif %}
      {% if aromaticAtomCount is defined and aromaticAtomCount %}--aromaticAtomCount{% endif %}
      {% if rotatableBondCount is defined and rotatableBondCount %}--rotatableBondCount{% endif %}
    variables:
      order:
        options:
        - outputFile
        - header
        - molecularWeight
        - molecularFormula
        - atomCount
        - heavyAtomCount
        - bondCount
        - logp
        - logd
        - hbd
        - hba
        - ringCount
        - ringAtomCount
        - aromaticRingCount
        - aromaticAtomCount
        - rotatableBondCount
      inputs:
        type: object
        required:
        - inputFile
        properties:
          inputFile:
            title: Input molecules
            mime-types:
            - chemical/x-mdl-sdfile
            - squonk/x-smiles
            - text/csv
            type: file
      outputs:
        type: object
        properties:
          results:
            title: Output file name
            mime-types:
            - chemical/x-mdl-sdfile
            creates: '{{ outputFile }}'
            type: file
            annotation-properties:
              fields-descriptor:
                origin: squonk2-job
                description: ChemAxon simple molecular properties
                fields:
                  CXN_molecularWeight:
                    type: number
                    description: Molecular weight
                    required: false
                    active: true
                  CXN_molecularFormula:
                    type: string
                    description: Molecular formula
                    required: false
                    active: true
                  CXN_atomCount:
                    type: integer
                    description: Atom count
                    required: false
                    active: true
                  CXN_heavyAtomCount:
                    type: number
                    description: Heavy atom count
                    required: false
                    active: true
                  CXN_bondCount:
                    type: integer
                    description: Bond count
                    required: false
                    active: true
                  CXN_cLogp:
                    type: number
                    description: cLogP
                    required: false
                    active: true
                  CXN_logD:
                    type: number
                    description: logD at pH 7.4
                    required: false
                    active: true
                  CXN_donorCount:
                    type: integer
                    description: H-bond donor count
                    required: false
                    active: true
                  CXN_acceptorCount:
                    type: integer
                    description: H-bond acceptor count
                    required: false
                    active: true
                  CXN_ringCount:
                    type: integer
                    description: Ring count
                    required: false
                    active: true
                  CXN_ringAtomCount:
                    type: integer
                    description: Ring atom count
                    required: false
                    active: true
                  CXN_aromaticRingCount:
                    type: integer
                    description: Aromatic ring count
                    required: false
                    active: true
                  CXN_aromaticAtomCount:
                    type: integer
                    description: Aromatic atom count
                    required: false
                    active: true
                  CXN_rotatableBondCount:
                    type: integer
                    description: Rotatable bond count
                    required: false
                    active: true
              service-execution:
                service_ref: 'https://discourse.squonk.it/t/job-cdk-molecular-descriptors/126'
              derived-from: inputFile
      options:
        type: object
        required:
        - outputFile
        properties:
          outputFile:
            title: Output file (.sdf)
            type: string
            default: cxn-molprops.sdf
            pattern: "^[A-Za-z0-9_/\\.\\-]+$"
          header:
            title: Include header for .smi output
            type: boolean
            default: true
          molecularWeight:
            title: Calculate molecular weight
            type: boolean
            default: true
          molecularFormula:
            title: Calculate molecular formula
            type: boolean
            default: true
          atomCount:
            title: Calculate atom count
            type: boolean
            default: true
          heavyAtomCount:
            title: Calculate heavy atom count
            type: boolean
            default: true
          bondCount:
            title: Calculate bond count
            type: boolean
            default: true
          logp:
            title: Calculate LogP
            type: boolean
            default: true
          logd:
            title: Calculate LogD at ph 7.4
            type: boolean
            default: true
          hbd:
            title: Calculate H-bond donors
            type: boolean
            default: true
          hba:
            title: Calculate H-bond acceptors
            type: boolean
            default: true
          ringCount:
            title: Calculate ring count
            type: boolean
            default: true
          ringAtomCount:
            title: Calculate ring atom count
            type: boolean
            default: true
          aromaticRingCount:
            title: Calculate aromatic ring count
            type: boolean
            default: true
          aromaticAtomCount:
            title: Calculate aromatic atom count
            type: boolean
            default: true
          rotatableBondCount:
            title: Calculate rotatable bond count
            type: boolean
            default: true
    tests:
      simple-execution:
        inputs:
          inputFile: data/dhfr_3d-10.sdf
        options:
          outputFile: foo/cxn-predictions.sdf
          molecularWeight: true
          molecularFormula: true
          atomCount: true
          heavyAtomCount: true
          bondCount: true
          logp: true
          logd: true
          hba: true
          hbd: true
          ringCount: true
          ringAtomCount: true
          aromaticRingCount: true
          aromaticAtomCount: true
          rotatableBondCount: true
        checks:
          exitCode: 0
          outputs:
          - name: foo/cxn-predictions.sdf
            checks:
            - exists: true

  chemaxon-molecular-props-logd:
    name: ChemAxon logD calculator
    description: >-
      Calculate logD using ChemAxon tools.
    version: '1.0.0'
    category: molecular properties
    keywords:
    - chemaxon
    - properties
    - logd
    image:
      name: informaticsmatters/squonk2-chemaxon
      tag: latest
      project-directory: /data
      working-directory: /data
      fix-permissions: true
      file:
      - name: /usr/local/license.cxl
        content-from:
          account-server-asset:
            name: chemaxon-license-file
      environment:
      - name: CHEMAXON_LICENSE_URL
        value-from:
          constant:
            value: /usr/local/license.cxl
    # The container has no entrypoint so this is the command that is executed.
    # The CLASSPATH environment variable in the container is set.
    command: >-
      java squonk.jobs.chemaxon.LogDCalc
      --input '{{ inputFile }}'
      --output '{{ outputFile }}'
      {% if header is defined %}--header {{ header }}{% endif %}
      --ph {{ ph }}
      {% if minValue is defined %}--min-value {{ minValue }}{% endif %}
      {% if maxValue is defined %}--max-value {{ maxValue }}{% endif %}
    variables:
      order:
        options:
        - outputFile
        - header
        - ph
        - minValue
        - maxValue
      inputs:
        type: object
        required:
        - inputFile
        properties:
          inputFile:
            title: Input molecules
            mime-types:
            - chemical/x-mdl-sdfile
            - squonk/x-smiles
            - text/csv
            type: file
      outputs:
        type: object
        properties:
          results:
            title: Output file name
            mime-types:
            - chemical/x-mdl-sdfile
            creates: '{{ outputFile }}'
            type: file
            annotation-properties:
              fields-descriptor:
                origin: squonk2-job
                description: ChemAxon logD calculator
                fields:
                  CXN_logD:
                    type: number
                    description: >-
                      logD at pH {{ ph }}
                    required: false
                    active: true
              service-execution:
                service_ref: 'https://discourse.squonk.it/t/job-cdk-molecular-descriptors/126'
              derived-from: inputFile
      options:
        type: object
        required:
        - outputFile
        - ph
        properties:
          outputFile:
            title: Output file (.sdf)
            type: string
            default: cxn-logd.sdf
            pattern: "^[A-Za-z0-9_/\\.\\-]+$"
          header:
            title: Include header for .smi output
            type: boolean
            default: true
          ph:
            title: pH
            type: number
            default: 7.4
            minimum: 0
            maximum: 14
          minValue:
            title: Min value
            type: number
          maxValue:
            title: Max value
            type: number
    tests:
      simple-execution:
        inputs:
          inputFile: data/dhfr_3d-10.sdf
        options:
          outputFile: foo/cxn-logd.sdf
          ph: 6.6
          minValue: 2.5
        checks:
          exitCode: 0
          outputs:
          - name: foo/cxn-logd.sdf
            checks:
            - exists: true
            - exists: true
